# Generated by Django 3.0.7 on 2021-01-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_technicalsupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='found',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
    ]
