# Generated by Django 3.1.5 on 2021-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20210109_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamkeensupply',
            name='depend',
        ),
        migrations.AlterField(
            model_name='tamkeensupply',
            name='tamkeen_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'تمكين منتهى بتدريب'), (2, 'تمكين منتهى بمقابل مادى'), (3, 'تمكين منتهى بفرصة عمل'), (4, 'غير مرشح')], null=True),
        ),
    ]
