# Generated by Django 3.1.6 on 2021-02-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20210205_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamkeenpayment',
            name='cases',
            field=models.ManyToManyField(blank=True, null=True, to='cases.TamkeenSupply'),
        ),
        migrations.AlterField(
            model_name='tamkeenpayment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.tamkeencourses'),
        ),
    ]
