# Generated by Django 3.1.6 on 2021-02-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_courses_tamkeen'),
        ('cases', '0020_auto_20210212_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamkeenpayment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.courses'),
        ),
        migrations.DeleteModel(
            name='TamkeenCourses',
        ),
    ]
