# Generated by Django 3.1.6 on 2021-02-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20210213_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeedyCase',
        ),
    ]
