# Generated by Django 3.1.1 on 2020-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='porfile-pic.png', null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
