# Generated by Django 3.1.5 on 2021-01-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201208_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدير المؤسسه'), (2, 'مشرف جمعيه رئيسيه'), (3, 'مشرف جمعيه تنمويه'), (4, 'مشرف متعاون'), (5, 'محتاج'), (6, 'متبرع'), (7, 'متطوع'), (8, 'متدرب'), (9, 'مدرب')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
