# Generated by Django 3.1.2 on 2020-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_needy',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدير المؤسسه'), (2, 'مشرف الجمعيه'), (3, 'متبرع')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
