# Generated by Django 3.1.2 on 2020-10-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201031_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premier_emp',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a Premier Employee. ', verbose_name='Premier Employee '),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_secondary_emp',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an Secondary Employee. ', verbose_name='Secondary Employee'),
        ),
    ]
