# Generated by Django 3.1.2 on 2020-11-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201101_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_helper_employee',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an Helper Employee. ', verbose_name='Helper Employee '),
        ),
        migrations.AddField(
            model_name='user',
            name='is_needy',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an Needy. ', verbose_name='Needy '),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدير المؤسسه'), (2, 'مشرف جمعيه رئيسيه'), (3, 'مشرف جمعيه تنمويه'), (4, 'مشرف متعاون'), (5, 'محتاج')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
