# Generated by Django 3.1.2 on 2020-10-23 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='عن المؤسسه'),
        ),
        migrations.RemoveField(
            model_name='foundation',
            name='employee',
        ),
        migrations.AddField(
            model_name='foundation',
            name='employee',
            field=models.ManyToManyField(related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='مشرفيين'),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المؤسسه'),
        ),
    ]
