# Generated by Django 3.1.2 on 2020-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20201023_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='النوع')),
                ('stage', models.SmallIntegerField(choices=[(1, 'التمهيدى'), (2, 'الأبتدائى'), (3, 'الأعدادى'), (4, 'الثانوى'), (5, 'الجامعه')], verbose_name='المرحله')),
                ('age', models.SmallIntegerField(null=True, verbose_name='العمر')),
            ],
        ),
        migrations.RemoveField(
            model_name='needy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='needy',
            name='description',
        ),
        migrations.AddField(
            model_name='needy',
            name='age',
            field=models.SmallIntegerField(null=True, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='needy',
            name='case_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needy',
            name='data_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='needy',
            name='health_status',
            field=models.SmallIntegerField(choices=[(1, 'مريض'), (1, 'حالة حرجة'), (1, 'راتب شهري')], null=True, verbose_name='الحاله الصحيه'),
        ),
        migrations.AddField(
            model_name='needy',
            name='home',
            field=models.SmallIntegerField(choices=[(1, 'ملك'), (2, 'إيجار'), (3, 'أخرى')], null=True, verbose_name='السكن'),
        ),
        migrations.AddField(
            model_name='needy',
            name='source_income',
            field=models.SmallIntegerField(choices=[(1, 'راتب شهري'), (2, 'ضمان اجتماعي'), (3, 'حساب مواطن'), (4, 'اخرى ')], null=True, verbose_name='وصف الحاله'),
        ),
        migrations.AddField(
            model_name='needy',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='national_id',
            field=models.CharField(max_length=255, null=True, verbose_name='رقم الهويه'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='needy',
            name='dependencies',
            field=models.ManyToManyField(to='office.Dependency', verbose_name='العائلين'),
        ),
    ]
