# Generated by Django 3.1.2 on 2020-10-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20201026_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='health_status',
            field=models.SmallIntegerField(choices=[(1, 'مريض'), (2, 'حالة حرجة'), (3, 'صحة جيدة')], null=True, verbose_name='الحاله الصحيه'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='source_income',
            field=models.SmallIntegerField(choices=[(1, 'راتب شهري'), (2, 'ضمان اجتماعي'), (3, 'حساب مواطن'), (4, 'اخرى ')], null=True, verbose_name='مصدر الدخل'),
        ),
    ]
