# Generated by Django 3.1.2 on 2020-10-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20201031_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المؤسسه'),
        ),
    ]
