# Generated by Django 3.1.2 on 2020-10-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20201101_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المؤسسه'),
        ),
    ]
