# Generated by Django 3.1.2 on 2020-10-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20201101_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='stage',
            field=models.CharField(choices=[('التمهيدى', 'التمهيدى'), ('الأبتدائى', 'الأبتدائى'), ('الأعدادى', 'الأعدادى'), ('الثانوى', 'الثانوى'), ('الجامعه', 'الجامعه')], max_length=255, verbose_name='المرحله'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='health_status',
            field=models.CharField(choices=[('مريض', 'مريض'), ('حالة حرجة', 'حالة حرجة'), ('صحة جيدة', 'صحة جيدة')], max_length=255, null=True, verbose_name='الحاله الصحيه'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='home',
            field=models.SmallIntegerField(choices=[('ملك', 'ملك'), ('إيجار', 'إيجار'), ('أخرى', 'أخرى')], null=True, verbose_name='السكن'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='source_income',
            field=models.CharField(choices=[('راتب شهري', 'راتب شهري'), ('ضمان اجتماعي', 'ضمان اجتماعي'), ('حساب مواطن', 'حساب مواطن'), ('اخرى ', 'اخرى ')], max_length=255, null=True, verbose_name='مصدر الدخل'),
        ),
    ]
