# Generated by Django 3.0.7 on 2021-01-09 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0007_auto_20201225_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم الدوره')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='عن الدوره')),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='المسار')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCourseBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.CourseBag', verbose_name='الحقيبه')),
                ('needy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Needy', verbose_name='المستفيد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
