# Generated by Django 3.1.2 on 2020-10-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20201101_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='home',
            field=models.CharField(choices=[('ملك', 'ملك'), ('إيجار', 'إيجار'), ('أخرى', 'أخرى')], max_length=255, null=True, verbose_name='السكن'),
        ),
    ]
