# Generated by Django 3.1.2 on 2020-11-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20201101_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='amount',
            field=models.CharField(max_length=255, null=True, verbose_name='قيمة الدعم'),
        ),
        migrations.AddField(
            model_name='needy',
            name='department',
            field=models.CharField(max_length=255, null=True, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='needy',
            name='emp_name',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المشرف'),
        ),
        migrations.AddField(
            model_name='needy',
            name='parent',
            field=models.CharField(max_length=255, null=True, verbose_name='العائل'),
        ),
        migrations.AddField(
            model_name='needy',
            name='pay_paper',
            field=models.FileField(default='<function now at 0x03FED028>', upload_to='', verbose_name='سند الصرف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needy',
            name='support',
            field=models.CharField(max_length=255, null=True, verbose_name='الدعم المقدم'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='dependencies',
            field=models.ManyToManyField(to='office.Dependency', verbose_name='الاطفال'),
        ),
    ]
