# Generated by Django 3.0.7 on 2021-01-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_coursebag_paymentcoursebag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.FileField(blank=True, null=True, upload_to='', verbose_name='سند الصرف')),
                ('needy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.Needy', verbose_name='المستفيد')),
            ],
        ),
        migrations.CreateModel(
            name='BagCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='الشهاده')),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.Courses', verbose_name='الحقيبه')),
                ('needy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.Needy', verbose_name='المستفيد')),
            ],
        ),
    ]
