# Generated by Django 3.1.2 on 2020-11-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20201103_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='pay_paper',
        ),
    ]
