# Generated by Django 3.1.5 on 2021-01-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_bagcertificate_payticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='enablity',
        ),
        migrations.RemoveField(
            model_name='needy',
            name='enablity',
        ),
    ]
