# Generated by Django 3.1.2 on 2020-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_remove_needy_pay_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='enablity',
            field=models.SmallIntegerField(choices=[(1, 'مرشح للتمكين'), (2, 'غير مرشح للتمكين')], null=True),
        ),
        migrations.AddField(
            model_name='needy',
            name='enablity',
            field=models.SmallIntegerField(choices=[(1, 'مرشح للتمكين'), (2, 'غير مرشح للتمكين')], null=True),
        ),
    ]
