# Generated by Django 3.1.5 on 2021-01-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_auto_20210116_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='depend_child',
        ),
        migrations.AddField(
            model_name='coursebag',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاريخ النهايه'),
        ),
        migrations.AddField(
            model_name='coursebag',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاريخ البدايه'),
        ),
        migrations.AddField(
            model_name='courses',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاريخ النهايه'),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاريخ البدايه'),
        ),
    ]
