# Generated by Django 3.1.5 on 2021-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_auto_20210116_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebag',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الساعات'),
        ),
    ]
