# Generated by Django 3.1.2 on 2020-11-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_auto_20201115_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='job',
            field=models.CharField(max_length=255, null=True, verbose_name='المهنه'),
        ),
    ]
