# Generated by Django 3.1.5 on 2021-01-19 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0012_coursebag_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebag',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='المدرب'),
            preserve_default=False,
        ),
    ]
