# Generated by Django 3.1.2 on 2020-11-17 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0012_needy_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم الدوره')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='عن الدوره')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم الراعى')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='الجوال')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='عن المؤسسه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
