# Generated by Django 3.1.5 on 2021-01-24 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0013_coursebag_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ اﻷضافه')),
                ('foundation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.foundation', verbose_name='المؤسسه')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المشارك')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.provider', verbose_name='الداعم')),
            ],
        ),
    ]
