# Generated by Django 3.1.2 on 2020-11-21 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0013_courses_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='cases',
            field=models.ManyToManyField(null=True, related_name='case', to='office.Needy', verbose_name='الحالات'),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='employee',
            field=models.ManyToManyField(null=True, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='مشرفيين'),
        ),
    ]
