# Generated by Django 3.1.2 on 2020-11-26 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0014_auto_20201121_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cases',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='الحاله المستحقه'),
        ),
        migrations.AddField(
            model_name='courses',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.provider', verbose_name='الراعى'),
        ),
    ]
