# Generated by Django 3.1.5 on 2021-01-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_greenparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebag',
            name='green',
            field=models.ManyToManyField(to='office.GreenParticipant', verbose_name='المشاركين'),
        ),
    ]
