# Generated by Django 3.1.5 on 2021-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_coursebag_green'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebag',
            name='green',
            field=models.ManyToManyField(blank=True, null=True, to='office.GreenParticipant', verbose_name='المشاركين'),
        ),
    ]
