# Generated by Django 3.1.5 on 2021-01-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_auto_20210125_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebag',
            name='foundation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.foundation', verbose_name='المؤسسه'),
        ),
    ]
