# Generated by Django 3.1.5 on 2021-02-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_coursebag_foundation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='cases',
        ),
    ]
