# Generated by Django 3.1.6 on 2021-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_remove_courses_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tamkeen',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'تمكين منتهى بمقابل مادى'), (2, 'تمكين منتهى بتوظيف')], null=True),
        ),
    ]
