# Generated by Django 3.1.6 on 2021-02-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_courses_tamkeen'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='السعر'),
        ),
    ]
