# Generated by Django 3.1.6 on 2021-02-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='عرض الحاله'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='support',
            field=models.SmallIntegerField(choices=[(1, 'دعم الكهرباء'), (2, 'دعم الغذاء'), (3, 'دعم التعليم'), (4, 'دعم الماء'), (5, 'دعم الصحة'), (6, 'دعم اﻷيجار')], max_length=255, null=True, verbose_name='الدعم المقدم'),
        ),
    ]
