# Generated by Django 3.1.6 on 2021-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0021_auto_20210214_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='total_donations',
        ),
        migrations.AddField(
            model_name='needy',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
