# Generated by Django 3.1.7 on 2021-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0024_coursebag_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebag',
            name='duration',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
